- hosts: ubuntu22 
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes    

    - name: Installing Apache, tree and git packages
      apt:
        name:
          - apache2
          - tree
          - git
        state: latest

    - name: Start Apache and enable 
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create groups kaizen, devops, qa
      group:
        name: "{{ item }}"
        state: present
      loop:
        - kaizen
        - devops
        - qa

    - name: Creating user Mairambek and add to kaizen and qa groups
      user:
        name: Mairambek
        groups: qa,kaizen
        append: yes
    
    - name: Creating user tester and add to the qa group
      user:
        name: tester
        group: qa
        append: yes

    - name: Copy files from Homework1 folder to remote ubuntu22 machine
      copy:
        src: "./"
        dest: /root/
     